version: "3"

services:
  app:
    container_name: crud-api
    build: .
    ports:
      - 443:8080
      - 80:8080
    restart: on-failure
    environment:
      PORT: 8080
      MONGODB_URL: "mongodb://db:27017"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
